config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.benchmark-runner:
      branch: main
      repo: https://github.com/cessda/cessda.cmv.benchmark-runner.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.benchmark-runner git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-corn-mastiff.sh
        container: qc.acc_skimpy-aqua-dolphin
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.benchmark-runner find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-tan-insect.sh
        container: qc.doc_skanky-maroon-lynx
      github.com/cessda/cessda.cmv.benchmark-runner git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-chestnut-coati.sh
        container: qc.doc_slaphappy-olivine-rat
      github.com/cessda/cessda.cmv.benchmark-runner markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-scarlet-russel.sh
        container: qc.doc_sleepy-cinnamon-butterfly
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.benchmark-runner licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-azure-moth.sh
        container: qc.lic_hasty-purple-tetra
  QC.Met:
    repos:
      github.com/cessda/cessda.cmv.benchmark-runner cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-maroon-markhor.sh
        container: qc.met_sickly-razzmatazz-bracke
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv.benchmark-runner checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cream-oyster.sh
        container: qc.sty_clammy-cinnamon-mist
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.benchmark-runner get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-wisteria-hedgehog.sh
        container: qc.ver_hilly-scarlet-vole
timeout: 5400
